grafana:
    env:
        GF_SERVER_ROOT_URL: http://grafana.homelab.local/
    persistence:
        enabled: false
    grafana.ini:
        session:
            provider: database
        database:
            type: postgres
            host: postgres.monitoring.svc.cluster.local:5432
            name: grafana
            user: grafana
            ssl_mode: disable
    envFromSecret: grafana-db
    ingress:
        enabled: true
        ingressClassName: nginx
        hosts: ["grafana.homelab.local"]
        path: /

prometheus:
    prometheusSpec:
        retention: 1d
        retentionSize: 4.5GB
        walCompression: true
        storageSpec:
            volumeClaimTemplate:
                spec:
                    storageClassName: longhorn
                    resources:
                        requests:
                            storage: 5Gi
    ingress:
        enabled: true
        ingressClassName: nginx
        hosts: ["prometheus.homelab.local"]
        paths: ["/"]

alertmanager:
    alertmanagerSpec:
        storage:
            volumeClaimTemplate:
                spec:
                    storageClassName: longhorn
                    resources:
                        requests:
                            storage: 2Gi
