{
 "title": "Media Server Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus DS", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total, instance)"
    }
   },
   {
    "name": "gpu_instance",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP, instance)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU index",
    "query": {
     "query": "label_values(DCGM_FI_DEV_POWER_USAGE{instance=~\"$gpu_instance\"}, gpu)"
    }
   },
   {
    "name": "diskdevices",
    "label": "Disk devices",
    "query": {
     "query": "label_values(node_disk_read_bytes_total{instance=\"$instance\"}, device)"
    }
   },
   {
    "name": "smart_device",
    "query": {
     "query": "label_values(smartctl_device_temperature{temperature_type=\"current\"}, device)"
    }
   },
   { "name": "hdd_normal_max", "label": "HDD normal max (°C)", "query": "40" },
   { "name": "hdd_warn", "label": "HDD warn (°C)", "query": "45" },
   { "name": "hdd_red", "label": "HDD red (°C)", "query": "55" },
   { "name": "hdd_max", "label": "HDD max (°C)", "query": "60" },
   { "name": "nvme_normal_max", "label": "NVMe normal (°C)", "query": "70" },
   { "name": "nvme_warn_offset", "label": "NVMe warn offset (°C)", "query": "5" },
   { "name": "cpu_normal_max", "label": "CPU normal (°C)", "query": "75" },
   { "name": "cpu_warn", "label": "CPU warn (°C)", "query": "85" },
   { "name": "cpu_red", "label": "CPU red (°C)", "query": "90" },
   { "name": "cpu_max", "label": "CPU max (°C)", "query": "100" },
   { "name": "gpu_normal_max", "label": "GPU normal (°C)", "query": "75" },
   { "name": "gpu_warn", "label": "GPU warn (°C)", "query": "85" },
   { "name": "gpu_red", "label": "GPU red (°C)", "query": "90" },
   { "name": "gpu_max", "label": "GPU max (°C)", "query": "95" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(play_seconds_total, job)"
   },
   {
    "name": "server",
    "label": "server",
    "query": "label_values(play_seconds_total{job=~\"$job\"}, server)"
   },
   {
    "name": "plex_instance",
    "label": "plex instance",
    "query": "label_values(play_seconds_total{job=~\"$job\"}, instance)"
   },
   {
    "name": "cores",
    "query": {
     "query": "query_result(scalar(count(count by (package, core) (node_cpu_info{instance=\"$instance\"}))))"
    }
   },
   {
    "name": "threads",
    "query": {
     "query": "query_result(scalar(count(count by (cpu) (node_cpu_info{instance=\"$instance\"}))))"
    }
   },
   {
    "name": "igpu_instance",
    "query": {
     "query": "label_values(igpu_frequency_actual{job=\"intel-gpu\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (model_name) (node_cpu_info{instance=\"$instance\"})",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_info{instance=\"$instance\"}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\"} - node_boot_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "All Movies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Movies" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "plex_media_movies{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\"}\n\n",
     "legendFormat": "{{library}}"
    }
   ]
  },
  {
   "title": "All Shows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Episodes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "plex_media_episodes{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\"}\n\n",
     "legendFormat": "{{library}}"
    }
   ]
  },
  {
   "title": "Library Storage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(library_storage_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\"}) by (library)",
     "legendFormat": "{{library}}"
    }
   ]
  },
  {
   "title": "Platform Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "server_info{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\"}",
     "legendFormat": "{{platform}} - {{platform_version}}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Plex Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "server_info{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Library Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(library_duration_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\"}) by (library)",
     "legendFormat": "{{library}}"
    }
   ]
  },
  {
   "title": "CPU Utilization (current)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "RAM Used (current)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$instance\"} / node_memory_MemTotal_bytes{instance=\"$instance\"})) * 100"
    }
   ]
  },
  {
   "title": "Network Download",
   "type": "stat",
   "description": "Incoming network traffic per interface",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  irate(node_network_receive_bytes_total{\n    job=\"node\", instance=\"$instance\",\n    device=~\"^(enp|ens|eno|eth|bond|wlp).*\"\n  }[$__rate_interval]) * 8\n)\n",
     "legendFormat": "{{device}} - Rx in"
    }
   ]
  },
  {
   "title": "Network Upload",
   "type": "stat",
   "description": "Outgoing network traffic per interface",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  irate(node_network_transmit_bytes_total{\n    job=\"node\", instance=\"$instance\",\n    device=~\"^(enp|ens|eno|eth|bond|wlp).*\"\n  }[$__rate_interval]) * 8\n)\n",
     "legendFormat": "{{device}} - Tx out"
    }
   ]
  },
  {
   "title": "Stream Counts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count( sum by (session) ( rate(play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", stream_type=~\"(transcode|directplay|DirectPlay)\"}[$__rate_interval]) ) > 0 ) or on() vector(0)",
     "legendFormat": "Total Streams"
    },
    {
     "expr": "count( sum by (session) ( rate(play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", stream_type=~\"(directplay|DirectPlay)\"}[$__rate_interval]) ) > 0 ) or on() vector(0)",
     "legendFormat": "Direct Play"
    },
    {
     "expr": "count( sum by (session) ( rate(play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", stream_type=\"transcode\", transcode_type=~\"(video|both)\"}[$__rate_interval]) ) > 0 ) or on() vector(0)",
     "legendFormat": "Video Transcodes"
    },
    {
     "expr": "count( sum by (session) ( rate(play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", stream_type=\"transcode\", transcode_type=~\"(audio|both)\"}[$__rate_interval]) ) > 0 ) or on() vector(0)",
     "legendFormat": "Audio Transcodes"
    },
    {
     "expr": "count( sum by (session) ( rate(play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", subtitle_action=\"transcode\"}[$__rate_interval]) ) > 0 ) or on() vector(0)",
     "legendFormat": "Subtitle Transcode"
    },
    {
     "expr": "count( sum by (session) ( rate(play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", subtitle_action=\"burn\"}[$__rate_interval]) ) > 0 ) or on() vector(0)",
     "legendFormat": "Subtitle Burn"
    }
   ]
  },
  {
   "title": "Now Playing (Sessions)",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (user, device_type, device, stream_resolution, stream_file_resolution, server, stream_bitrate, stream_type, what) ((label_join(label_join(rate(play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", media_type=\"episode\", stream_type!=\"\"}[45s]), \"what\", \" / \", \"title\", \"child_title\"), \"what\", \" / \", \"what\", \"grandchild_title\") or label_join(rate(play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", media_type!=\"episode\", stream_type!=\"\"}[45s]), \"what\", \"\", \"title\"))) > 0"
    }
   ]
  },
  {
   "title": "Package Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igpu_power_package{job=\"intel-gpu\", instance=\"$igpu_instance\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Render/3D Busy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igpu_engines_render_3d_0_busy{job=\"intel-gpu\", instance=\"$igpu_instance\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Video Busy",
   "type": "stat",
   "description": "GPU Decoder Utilization",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igpu_engines_video_0_busy{job=\"intel-gpu\", instance=\"$igpu_instance\"}",
     "legendFormat": "NVDEC {{gpu}}"
    }
   ]
  },
  {
   "title": "VideoEnhance Busy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igpu_engines_video_enhance_0_busy{job=\"intel-gpu\", instance=\"$igpu_instance\"}",
     "legendFormat": "NVENC {{gpu}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(max_over_time(play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\"}[24h])) by (library_type)",
     "legendFormat": "{{library_type}}"
    }
   ]
  },
  {
   "title": "Actual Frequency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igpu_frequency_actual{job=\"intel-gpu\", instance=\"$igpu_instance\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Requested Frequency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igpu_frequency_requested{job=\"intel-gpu\", instance=\"$igpu_instance\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "NVMe Controller Temp",
   "type": "stat",
   "description": "NVMe Controller Temperature",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_hwmon_temp_celsius{instance=\"$instance\", chip=~\"nvme_.*\"} * on (chip, sensor, instance) group_left(label) node_hwmon_sensor_label{instance=\"$instance\", label=\"Composite\"} * on (chip, instance) group_left(chip_name) node_hwmon_chip_names{instance=\"$instance\"})",
     "legendFormat": "{{chip_name}}-{{label}}"
    }
   ]
  },
  {
   "title": "Top 10 Titles by duration",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\"}[$__interval])) by (media_type, title)",
     "legendFormat": "{{title}}"
    }
   ]
  },
  {
   "title": "GPU Frequencies",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "igpu_frequency_actual{job=\"intel-gpu\", instance=\"$igpu_instance\"}",
     "legendFormat": "Actual Frequency"
    },
    {
     "expr": "igpu_frequency_requested{job=\"intel-gpu\", instance=\"$igpu_instance\"}",
     "legendFormat": "Requested Frequency"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "stat",
   "description": "CPU Temperature",
   "gridPos": { "h": 11, "w": 3, "x": 9, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_hwmon_temp_celsius{instance=\"$instance\"} * on (chip, sensor, instance) group_left(label) node_hwmon_sensor_label{instance=\"$instance\"} * on (chip, instance) group_left(chip_name) node_hwmon_chip_names{instance=\"$instance\", chip_name=~\"k10temp|coretemp\"})",
     "legendFormat": "{{chip_name}}-{{label}}"
    }
   ]
  },
  {
   "title": "Top 10 Platforms by duration",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\"}[$__interval])) by (media_type, device_type)",
     "legendFormat": "{{device_type}}"
    }
   ]
  },
  {
   "title": "Duration by source resolution",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    (\n      label_replace(\n        sum by (stream_type, stream_file_resolution) (\n          play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", stream_type!=\"\"}\n        ),\n        \"res\",\"2160\",\n        \"stream_file_resolution\",\"(?i)^4k$\"\n      )\n      or label_replace(\n        sum by (stream_type, stream_file_resolution) (\n          play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", stream_type!=\"\"}\n        ),\n        \"res\",\"480\",\n        \"stream_file_resolution\",\"(?i)^sd$\"\n      )\n      or label_replace(\n        sum by (stream_type, stream_file_resolution) (\n          play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", stream_type!=\"\"}\n        ),\n        \"res\",\"$1p\",\n        \"stream_file_resolution\",\"^([0-9]+)$\"\n      )\n      or label_replace(\n        sum by (stream_type, stream_file_resolution) (\n          play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", stream_type!=\"\"}\n        ),\n        \"res\",\"$1\",\n        \"stream_file_resolution\",\".*?([1-9][0-9]{2,3}).*\"\n      )\n      or label_replace(\n        sum by (stream_type, stream_file_resolution) (\n          play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", stream_type!=\"\"}\n        ),\n        \"res\",\"unknown\",\n        \"stream_file_resolution\",\"^$\"\n      )\n    )\n  [$__interval:])\n) by (stream_type, res)\n",
     "legendFormat": "{{res}}"
    }
   ]
  },
  {
   "title": "Duration by day of week",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\"}[$__interval])) by (media_type) * ignoring(day,dow) group_right\n\n label_replace(   \n label_replace(   \n label_replace(   \n label_replace(   \n label_replace(   \n label_replace(      \n label_replace(   \n count_values without() (\"day\", day_of_week(timestamp(\n      sum(increase(          \n         play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\"}          \n      [$__interval]))  by (media_type)\n    )\n  ))\n  ,\"dow\",\"Sunday\",\"day\",\"0\")\n  ,\"dow\",\"Monday\",\"day\",\"1\")\n  ,\"dow\",\"Tuesday\",\"day\",\"2\")\n  ,\"dow\",\"Wednesday\",\"day\",\"3\")\n  ,\"dow\",\"Thursday\",\"day\",\"4\")\n  ,\"dow\",\"Friday\",\"day\",\"5\")\n  ,\"dow\",\"Saturday\",\"day\",\"6\")\n"
    }
   ]
  },
  {
   "title": "Duration by streamed resolution",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    (\n      label_replace(\n        sum by (stream_type, stream_resolution) (\n          play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", stream_type!=\"\"}\n        ),\n        \"res\",\"2160\",\n        \"stream_resolution\",\"(?i)^4k$\"\n      )\n      or label_replace(\n        sum by (stream_type, stream_resolution) (\n          play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", stream_type!=\"\"}\n        ),\n        \"res\",\"480\",\n        \"stream_resolution\",\"(?i)^sd$\"\n      )\n      or label_replace(\n        sum by (stream_type, stream_resolution) (\n          play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", stream_type!=\"\"}\n        ),\n        \"res\",\"$1p\",\n        \"stream_resolution\",\"^([0-9]+)$\"\n      )\n      or label_replace(\n        sum by (stream_type, stream_resolution) (\n          play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", stream_type!=\"\"}\n        ),\n        \"res\",\"$1\",\n        \"stream_resolution\",\".*?([1-9][0-9]{2,3}).*\"\n      )\n      or label_replace(\n        sum by (stream_type, stream_resolution) (\n          play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\", stream_type!=\"\"}\n        ),\n        \"res\",\"unknown\",\n        \"stream_resolution\",\"^$\"\n      )\n    )\n  [$__interval:])\n) by (stream_type, res)\n",
     "legendFormat": "{{res}}"
    }
   ]
  },
  {
   "title": "Top 10 Users by duration",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(play_seconds_total{job=~\"$job\", instance=~\"$plex_instance\", server=~\"$server\"}[$__interval])) by (media_type, user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Incoming and outgoing network traffic per interface",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$instance\", device!=\"lo\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}} - Rx in"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$instance\", device!=\"lo\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}} - Tx out"
    }
   ]
  },
  {
   "title": "Busy Engines",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_render_3d_0_busy{job=\"intel-gpu\", instance=\"$igpu_instance\"}",
     "legendFormat": "Render/3D"
    },
    {
     "expr": "igpu_engines_blitter_0_busy{job=\"intel-gpu\", instance=\"$igpu_instance\"}",
     "legendFormat": "Blitter"
    },
    {
     "expr": "igpu_engines_video_0_busy{job=\"intel-gpu\", instance=\"$igpu_instance\"}",
     "legendFormat": "Video"
    },
    {
     "expr": "igpu_engines_video_enhance_0_busy{job=\"intel-gpu\", instance=\"$igpu_instance\"}",
     "legendFormat": "Video Enhance"
    }
   ]
  },
  {
   "title": "Disk Read/Write Data",
   "type": "timeseries",
   "description": "Number of bytes read from or written to the device per second",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$instance\", device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$instance\", device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write"
    }
   ]
  },
  {
   "title": "Temperature - All Sensors",
   "type": "timeseries",
   "description": "Combined temperature readings all devices with a sensor.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(node_hwmon_temp_celsius{instance=\"$instance\"} * on (chip, sensor, instance) group_left(label) node_hwmon_sensor_label{instance=\"$instance\"} * on (chip, instance) group_left(chip_name) node_hwmon_chip_names{instance=\"$instance\"}) > 0",
     "legendFormat": "{{chip_name}}-{{label}}"
    },
    {
     "expr": "((node_hwmon_temp_celsius{instance=\"$instance\"} unless on (chip, sensor, instance) node_hwmon_sensor_label{instance=\"$instance\"}) * on (chip, instance) group_left(chip_name) node_hwmon_chip_names{instance=\"$instance\"}) > 0",
     "legendFormat": "{{chip_name}}-{{sensor}}"
    },
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"$gpu_instance\"} > 0)",
     "legendFormat": "nvidia-{{modelName}}-GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "NVMe Controller Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(node_hwmon_temp_celsius{instance=\"$instance\", chip=~\"nvme_.*\"} * on (chip, sensor, instance) group_left(label) node_hwmon_sensor_label{instance=\"$instance\", label=\"Composite\"} * on (chip, instance) group_left(chip_name) node_hwmon_chip_names{instance=\"$instance\"})",
     "legendFormat": "{{chip_name}}-{{label}}"
    },
    {
     "expr": "(0 * node_time_seconds{instance=\"$instance\"}) + $nvme_normal_max",
     "legendFormat": "NVMe normal"
    },
    {
     "expr": "(node_hwmon_temp_max_celsius{instance=\"$instance\", chip=~\"nvme_.*\", sensor=\"temp1\"} - $nvme_warn_offset)",
     "legendFormat": "NVMe warn"
    },
    {
     "expr": "node_hwmon_temp_max_celsius{instance=\"$instance\", chip=~\"nvme_.*\", sensor=\"temp1\"}",
     "legendFormat": "NVMe red"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=\"$instance\", chip=~\"nvme_.*\", sensor=\"temp1\"}",
     "legendFormat": "NVMe max"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization",
   "type": "timeseries",
   "description": "Percentage of time the disk was actively processing I/O operations",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"$instance\", device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "CPU time spent busy vs idle, split by activity type",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\", mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "RAM and swap usage overview, including caches",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"} - (node_memory_Cached_bytes{instance=\"$instance\"} + node_memory_Buffers_bytes{instance=\"$instance\"} + node_memory_SReclaimable_bytes{instance=\"$instance\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\"} + node_memory_Buffers_bytes{instance=\"$instance\"} + node_memory_SReclaimable_bytes{instance=\"$instance\"}",
     "legendFormat": "Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\"} - node_memory_SwapFree_bytes{instance=\"$instance\"})",
     "legendFormat": "Swap used"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "I/O"
    },
    {
     "expr": "irate(node_pressure_irq_stalled_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Irq"
    }
   ]
  }
 ]
}