services:
    wg-easy:
        container_name: wg-easy
        image: ghcr.io/wg-easy/wg-easy:latest
        restart: unless-stopped

        ports:
            - "51820:51820/udp" # VPN
            - "51821:51821/tcp" # Web UI

        environment:
            - LANG=en
            - WG_HOST=vpn.andreaventi.com
            - PASSWORD_HASH=${WIREGUARD_ADMIN_PASSWORD_HASH}
            - WG_DEFAULT_ADDRESS=10.8.0.x
            - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
            - UI_TRAFFIC_STATS=true
            - UI_CHART_TYPE=2 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
            - WG_POST_UP=iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
            - WG_POST_DOWN=iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

        volumes:
            - /root/docker/vpn-stack/wg-easy-data:/etc/wireguard

        cap_add:
            - NET_ADMIN
            - SYS_MODULE

        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.all.src_valid_mark=1
