services:
    open-webui:
        image: ghcr.io/open-webui/open-webui:main
        container_name: open-webui
        restart: unless-stopped
        ports:
            - "8080:8080"
        environment:
            - OLLAMA_BASE_URL=http://host.docker.internal:11434
        volumes:
            - ${HOME}/docker-compose/open-webui:/app/backend/data

    searxng:
        image: searxng/searxng:latest
        container_name: searxng
        restart: unless-stopped
        ports:
            - "8888:8080" # expose on localhost:8888
        environment:
            - SEARXNG_BASE_URL=http://localhost:8888
        volumes:
            - ${HOME}/docker-compose/SearxNG:/etc/searxng
