apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: v1.33.4
clusterName: kubernetes
controlPlaneEndpoint: 10.0.10.200:6443
apiServer:
    certSANs:
        - 10.0.10.160 # master-01
        - 10.0.10.161 # master-02
        - 10.0.10.162 # master-03
        - 10.0.10.200 # VIP
        - k8s-master-01
        - k8s-master-02
        - k8s-master-03
networking:
    podSubnet: 10.244.0.0/16
    serviceSubnet: 10.96.0.0/12
etcd:
    local: { dataDir: /var/lib/etcd }
