apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    name: homelab-pool
    namespace: metallb-system
spec:
    addresses:
        - 10.0.10.240-10.0.10.254
    autoAssign: true
    avoidBuggyIPs: false
