global:
    scrape_interval: 15s
    evaluation_interval: 15s
    external_labels:
        cluster: homelab

scrape_configs:
    - job_name: prometheus
      static_configs:
          - targets: ["prometheus:9090"]

    - job_name: plex
      static_configs:
          - targets: ["prometheus-plex-exporter:9000"]

    - job_name: node
      static_configs:
          - targets: ["host.docker.internal:9100"]
          # using this because node_exporter is running in host network mode
      relabel_configs:
          - target_label: instance
            replacement: "node_exporter:9100"

    - job_name: intel-gpu
      file_sd_configs:
          - files: ["/etc/prometheus/file_sd/intel_gpu_targets.yml"]
            refresh_interval: 30s

    - job_name: smartctl
      static_configs:
          - targets: ["smartctl-exporter:9633"]

    - job_name: cadvisor
      static_configs:
          - targets: ["cadvisor:8080"]
