services:
    openwebui:
        image: ghcr.io/open-webui/open-webui:main
        container_name: openwebui
        restart: unless-stopped
        networks:
            - searxnet
        environment:
            ENABLE_PERSISTENT_CONFIG: false
            ENABLE_WEB_SEARCH: true
            WEB_SEARCH_ENGINE: "searxng"
            WEB_SEARCH_RESULT_COUNT: 3
            WEB_LOADER_CONCURRENT_REQUESTS: 10
            SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"
        ports:
            - "3010:8080"
        volumes:
            - ${HOME}/docker-compose/openwebui/openwebui-data:/app/backend/data

    searxng:
        container_name: searxng
        image: docker.io/searxng/searxng:latest
        restart: unless-stopped
        expose:
            - "8080"
        networks:
            - searxnet
        volumes:
            - ${HOME}/docker-compose/openwebui/searxng:/etc/searxng:rw
            - searxng-data:/var/cache/searxng:rw
        environment:
            - SEARXNG_HOSTNAME=localhost:8080/
            - SEARXNG_BASE_URL=http://localhost:8080/

networks:
    searxnet:
volumes:
    searxng-data:
