# If running on a privileged LXC container, add this as well to each container:
#       security_opt:
#         - apparmor=unconfined

services:
    beszel-agent:
        image: henrygd/beszel-agent:latest
        container_name: beszel-agent
        restart: unless-stopped
        network_mode: host
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./beszel_agent_data:/var/lib/beszel-agent
            # monitor other disks / partitions by mounting a folder in /extra-filesystems
            # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
        environment:
            LISTEN: 45876
            KEY: ${BESZEL_KEY}
            TOKEN: ${BESZEL_TOKEN}
            HUB_URL: http://<IP-OF-BESZEL-HUB-SERVER>:8090

    dockerproxy:
        image: ghcr.io/tecnativa/docker-socket-proxy:latest
        container_name: dockerproxy
        environment:
            - CONTAINERS=1
            - SERVICES=1
            - TASKS=1
            - POST=0
        ports:
            - 2375:2375
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped

    portainer-agent:
        image: portainer/agent:latest
        container_name: portainer-agent
        restart: always
        ports:
            - 9001:9001
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes

    dozzle-agent:
        image: amir20/dozzle:latest
        command: agent
        container_name: dozzle-agent
        environment:
            - DOZZLE_HOSTNAME=hostname
        ports:
            - 7007:7007
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped

    watchtower:
        container_name: watchtower
        image: containrrr/watchtower:latest
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: >
            --schedule "0 0 7 * * *"
            --cleanup
            --rolling-restart
            --log-level info
        # If you want metrics for something like getHomepage, set these:
        #   --http-api-metrics
        #   --http-api-token ${WATCHTOWER_HTTP_API_TOKEN}
        environment:
            WATCHTOWER_NOTIFICATIONS: slack
            WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: ${SLACK_WEBHOOK_URL}
            WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: "Watchtower"
            WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: "#watchtower"
            WATCHTOWER_NOTIFICATION_REPORT: "true"
            WATCHTOWER_NOTIFICATIONS_HOSTNAME: hostname
            WATCHTOWER_NOTIFICATION_TITLE_TAG: "hostname"
            WATCHTOWER_NOTIFICATION_TEMPLATE: |
                {{- if .Report -}}
                  {{- with .Report -}}
                {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed
                      {{- range .Updated}}
                - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
                      {{- end -}}
                      {{- range .Fresh}}
                - {{.Name}} ({{.ImageName}}): {{.State}}
                      {{- end -}}
                      {{- range .Skipped}}
                - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
                      {{- end -}}
                      {{- range .Failed}}
                - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
                      {{- end -}}
                  {{- end -}}
                {{- else -}}
                  {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
                {{- end -}}
