services:
    adguardhome:
        container_name: adguardhome
        image: adguard/adguardhome:latest
        restart: unless-stopped
        network_mode: host
        volumes:
            - /root/docker/dns-stack/adguardhome/work:/opt/adguardhome/work
            - /root/docker/dns-stack/adguardhome/conf:/opt/adguardhome/conf

    adguardhome-sync:
        container_name: adguardhome-sync
        image: ghcr.io/bakito/adguardhome-sync:latest
        restart: unless-stopped

        command: run
        ports:
            - "8080:8080"
        environment:
            LOG_LEVEL: info
            CRON: "0 */2 * * *"
            RUN_ON_START: "true"
            CONTINUE_ON_ERROR: "false"

            # Origin instance
            ORIGIN_URL: "${ORIGIN_URL}"
            ORIGIN_USERNAME: "${ADGUARD_HOME_USERNAME}"
            ORIGIN_PASSWORD: "${ADGUARD_HOME_PASSWORD}"

            # Replica 1
            REPLICA1_URL: "${REPLICA1_URL}"
            REPLICA1_USERNAME: "${ADGUARD_HOME_USERNAME}"
            REPLICA1_PASSWORD: "${ADGUARD_HOME_PASSWORD}"

            # API UI
            API_PORT: "8080"
            API_USERNAME: "${API_USERNAME}"
            API_PASSWORD: "${API_PASSWORD}"
            API_DARK_MODE: "true"

            # Enabled features (all true by default; define explicitly for clarity)
            FEATURES_GENERAL_SETTINGS: "true"
            FEATURES_QUERY_LOG_CONFIG: "true"
            FEATURES_STATS_CONFIG: "true"
            FEATURES_CLIENT_SETTINGS: "true"
            FEATURES_SERVICES: "true"
            FEATURES_FILTERS: "true"
            FEATURES_DHCP_SERVER_CONFIG: "true"
            FEATURES_DHCP_STATIC_LEASES: "true"
            FEATURES_DNS_SERVER_CONFIG: "true"
            FEATURES_DNS_ACCESS_LISTS: "true"
            FEATURES_DNS_REWRITES: "true"
            FEATURES_THEME: "true"
