services:
    gluetun:
        image: qmcgaw/gluetun:latest
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        environment:
            - TZ=America/New_York
            - UPDATER_PERIOD=24h
            - HEALTH_VPN_DURATION_INITIAL=120s
            # VPN
            - VPN_SERVICE_PROVIDER=airvpn
            - VPN_TYPE=wireguard
            - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
            - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
            - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
            - SERVER_COUNTRIES=United States
            # Firewall
            - FIREWALL_OUTBOUND_SUBNETS=${FIREWALL_OUTBOUND_SUBNETS}
            - FIREWALL_VPN_INPUT_PORTS=6881,14439
        ports:
            - 8000:8000 # Gluetun HTTP Control Server
            - 9865:9865 # qBittorrent Web UI
            - 6881:6881 # Torrent TCP
            - 6881:6881/udp # Torrent UDP
            - ${FIREWALL_VPN_INPUT_PORTS}:${FIREWALL_VPN_INPUT_PORTS} # AirVPN TCP
            - ${FIREWALL_VPN_INPUT_PORTS}:${FIREWALL_VPN_INPUT_PORTS}/udp # AirVPN UDP
        network_mode: bridge
        labels:
            - com.centurylinklabs.watchtower.enable=false
        security_opt:
            - no-new-privileges:true
        volumes:
            - /root/docker/media-vpn-stack/gluetun:/gluetun
            - /root/docker/media-vpn-stack/gluetun/auth/config.toml:/gluetun/auth/config.toml
        restart: always
        healthcheck:
            test: ["CMD", "sh", "-c", "nslookup google.com > /dev/null 2>&1"]
            interval: 10s
            timeout: 5s
            retries: 6
            start_period: 120s

    qbittorrent:
        image: ghcr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
            - TZ=America/New_York
            - PUID=0
            - PGID=0
            - WEBUI_PORT=9865
            - TORRENTING_PORT=${FIREWALL_VPN_INPUT_PORTS} # AirVPN Forwarded Port
        network_mode: service:gluetun
        labels:
            - deunhealth.restart.on.unhealthy=true
        security_opt:
            - no-new-privileges:true
        volumes:
            - /root/docker/media-vpn-stack/qbittorrent/config:/config
            - /mnt/nas-media/Downloads:/downloads
        depends_on:
            gluetun:
                condition: service_healthy
        entrypoint: >
            /bin/bash -c "
            echo 'Waiting for VPN DNS resolution via gluetun...';
            timeout 300 bash -c '
              until nslookup google.com >/dev/null 2>&1; do
                echo Waiting for DNS...;
                sleep 5;
              done
            ';
            if [ $? -ne 0 ]; then
              echo 'DNS check timed out. Exiting.';
              exit 1;
            fi;
            echo 'DNS working. Starting qBittorrent.';
            exec /init
            "
        tty: true
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-sSf", "https://1.1.1.1"]
            interval: 60s
            timeout: 10s
            retries: 3
            start_period: 20s

    deunhealth:
        image: qmcgaw/deunhealth
        container_name: deunhealth
        network_mode: "none"
        environment:
            - LOG_LEVEL=info
            - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
            - TZ=America/New_York
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
